title: Agência Traços
baseURL: /
params:
  description: A portfolio theme with a blog
  color_scheme: light
  accent_color: pink
  header:
    title: Exto
    has_nav: true
    nav_links:
      - label: Home
        url: /
        style: link
      - label: Portfolio
        url: /portfolio/
        style: link
      - label: Clipping
        url: /clipping/
        style: link
      - label: Style Guide
        url: /style-guide/
        style: link
      - label: Quem Somos
        url: /quem-somos/
        style: link
      - label: Contact
        url: /contact/
        style: link
  footer:
    content: >-
      COPYRIGHT TRAÇOS 2021 &copy;
    has_social: true
    social_links:
      - label: Facebook
        url: 'https://www.facebook.com/tracosprodutora'
        style: icon
        icon_class: fa-facebook
        new_window: true
      - label: Instagram
        url: 'https://www.instagram.com/tracosprodutora/'
        style: icon
        icon_class: fa-instagram
        new_window: true
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
